name: PR Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Comment PR
      if: ${{ failure() }}
      uses: actions/github-script@v4
      with:
        script: |
          const issue_number = context.issue.number;
          const message = 'Tests failed, please check your code.';
          github.rest.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
